---
apiVersion: v1
kind: Namespace
metadata:
  name: jemptrip

---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: jemptrip
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucmFtb2xhLnRvcCI6eyJ1c2VybmFtZSI6InNuYmVycnkiLCJwYXNzd29yZCI6IlFjazhdfktSU0EzX0s2VyIsImVtYWlsIjoiaW5mb0BoYXJib3IucmFtb2xhLnRvcCIsImF1dGgiOiJjMjVpWlhKeWVUcFJZMnM0WFg1TFVsTkJNMTlMTmxjPSJ9fX0=  # Replace with your actual base64 auth

---
# Site 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jemptrip
  namespace: jemptrip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jemptrip
  template:
    metadata:
      labels:
        app: jemptrip
    spec:
      containers:
      - name: jemptrip
        image: harbor.ramola.top/img/jemptrip:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: jemptrip-service
  namespace: jemptrip
spec:
  selector:
    app: jemptrip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jemptrip-ingress
  namespace: jemptrip
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: jemptrip.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jemptrip-service
            port:
              number: 80

  - host: www.jemptrip.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jemptrip-service
            port:
              number: 80
